server {
    listen 80;
    server_name demo.medimate.health.vn;

    location / {
        proxy_pass http://frontend:80; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Đảm bảo Nginx Proxy không tự ý xử lý file tĩnh, mà đẩy hết cho Frontend
    location /assets {
        proxy_pass http://frontend:80/assets;
        proxy_set_header Host $host;
    }
}